services:
  postgresdb:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
      - ./wrij-mbs-backend/init/:/docker-entrypoint-initdb.d/
  api-server:
    depends_on:
      - postgresdb
    build: ./wrij-mbs-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - $BACKEND_LOCAL_PORT:$EXPRESS_PORT
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_DOCKER_PORT
    stdin_open: true
    tty: true
  frontend-server:
    build: ./wrij-mbs-frontend
    restart: unless-stopped
    ports:
      - $FRONTEND_LOCAL_PORT:$NGINX_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./wrij-mbs-frontend:/app
    # command: npm start

volumes: 
  db: