/*CREATE TABLE tblMeetpakketten(
   Naam         VARCHAR(20) NOT NULL PRIMARY KEY
  ,Omschrijving VARCHAR(72) NOT NULL
  ,Valuta       VARCHAR(4) NOT NULL
  ,Stukprijs    INTEGER 
  ,Type         VARCHAR(10) NOT NULL
);*/
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('abs254','Absorptiebepaling bij 254nm','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('afvoer','Afvoerkostenfles','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('afwkg','Afwijking','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('agaw','Zilver','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('agbs','Zilver','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('agow','Zilver','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('agz1','Zilver','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('alaw','Aluminium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('albs','Aluminium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('alggp','Bedekking algen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('alow','Aluminium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('alz1','Aluminium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('asaw','Arseen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('asbs','Arseen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('asow','Arseen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('asz1','Arseen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('baaw','Barium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('babs','Barium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bacdrijf','Categorie Cyanobacteriedrijflaag','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('badgt','Badgasten','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('baow','Barium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('baw','Boor','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('baz1','Barium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('beaw','Beryllium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem','Bemonstering','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bemad-boot','additionele kosten bemonstering m.b.v. boot','ILOW',40,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bemad-fyto','additionele kosten fytoplankton bemonstering','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bemad-hybi','Toeslag combinatie hydrobiologische bemonstering','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-aw','Bemonstering Afvalwater (RioolWaterZuiveringsInstallaties)','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-awi','Instellen monsterkast','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-awi-icmb','Instellen monsterkast na monsterneming','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-awil','Locatiebezoek rwzi instellen.','ILOW',40,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-awml','Locatiebezoek bemonsteren','ILOW',40,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-bs','Bemonstering Waterbodem','ILOW',120,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-gw','Bemonstering Grondwater (peilbuizen)','ILOW',25,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-gwl','Starttarief Bemonstering Grondwater (peilbuizen)','ILOW',70,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-hybi','Bemonstering Hydrobiologie','ILOW',40,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-hybiloc','Locatiebezoek hydrobiologie monstername niet mogelijk','ILOW',40,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-meng','Mengen in het veld','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem-ow','Bemonstering Oppervlaktewater','ILOW',40,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bem2p','Bemonstering door 2 personen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('beow','Beryllium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bez1','Bezinksel','ILOW',4,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('biomatonb','Biologisch materiaal onbekend','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('blauwalgbio','Cyanobacterien Biovolume','ILOW',70,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('blauwalgdrijf','Cyanobacterien Drijflaag','ILOW',30,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('blauwalgprescn','Cyanobacterien PreScan','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('blauwalgv','Blauwalg veldmeting algentoorts','ILOW',22,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('boorbeschrijving','Boorbeschrijving Terra index','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bow','Boor','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('brandverzs','Brandvertragers in zwevende stof','ILOW',180,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('btexn','Aromaten (BTEXN)','ILOW',40,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('bzv','Biochemisch zuurstofverbruik (als O2) over 5 dagen','ILOW',12,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('caaw','Calcium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('cabs','Calcium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('caco','Calciumcarbonaat','ILOW',10,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('caco3','Calciumcarbonaat','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('caow','Calcium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('caz1','Calcium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('cdaw','Cadmium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('cdbs','Cadmium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('cdow','Cadmium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('cdz1','Cadmium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('chla','Chlorofyl','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('chlav','Totaal chlorofyl veldmeting algentoorts','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('cl','Chloride','ILOW',6,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('clg','Chloride','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('coaw','Kobalt','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('cobs','Kobalt','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('coow','Kobalt','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('coz1','Kobalt','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('craw','Chroom','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('crbs','Chroom','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('crow','Chroom','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('crz1','Chroom','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('cuaw','Koper','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('cubs','Koper','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('cuow','Koper','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('cuz1','Koper','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('czv','Chemisch zuurstofverbruik (als O2)','ILOW',13,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('czvcuv','Chemisch zuurstofverbruik (als O2) cuvettentest','ILOW',8,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('czvg','Chemisch zuurstofverbruik (als O2)','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('datarapport','Datarapporten uitleveren Hydrobiologie','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('debbeg','Debiet Begin','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('debdag','Debiet per dag','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('debeind','Debiet Eind','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('debiet','Debiet','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('debnetto','Netto Debiet','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('debuur','Debiet per uur','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dest','Ontsluiting metalen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('diato-bem','Diatomeeën bemonstering','ILOW',40,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('diato-bem-kn','Diatomeeën bemonstering (Knijp-methode)','ILOW',40,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('diato-bem-nt','Diatomeeën bemonstering (Net-methode)','ILOW',40,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('diepte','Diepte','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-acutus','DNA Procambarus acutus','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-anatoxine','Anatoxine producerende genen (aantal gen-kopieen)','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-bever','DNA bever','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-beverrat','DNA Beverrat','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-cabomba','DNA Cabomba','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-clarkii','DNA Procambarus clarkii','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-cylindrospermops','Cylindrospermopsine producerende genen (aantal gen-kopieen)','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-drdmictparv','DNA microthrix parvicella (draadvormer)','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-drdprofil','DNA candidatus promineofilum (draadvormer)','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-eikpcrups','DNA Eikenprocessierups','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-gmod','DNA Grote modderkruiper','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-leniusculus','DNA Pacifastacus leniusculus','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-limosus','DNA Orconectus limosus','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-microcystine','Microcystine producerende genen (aantal gen-kopieen)','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-muskrt','DNA muskusrat','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-paprika','DNA Paprika','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-rannvrs','DNA Ranavirus','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-saxotoxine','Saxotoxine producerende genen (aantal gen-kopieen)','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-tomaat','DNA Tomaat','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-trichbhzia','DNA Trichobilharzia','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-vb','Monstervoorbehandeling DNA','ILOW',50,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-vederkruid','DNA Vederkruid','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-virginalis','DNA Procambarus virginalis','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dna-virilis','DNA Orconectes virilis','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dnb','Opgelost organisch en anorganisch gebonden stikstof','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('doc','Opgelost organisch koolstof','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('doorz','Doorzicht (Ø 20 cm/six holes)','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('drijf','Bedekking drijflaag vegetatie','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('droogslo','Droogstand watergang','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('droogval','Droogvallingsgraad','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ds2','Percentage droge stof (t.b.v. lutum)','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dummy','Dummy test: i.v.m. niet te koppelen testen.','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('dvp','Diepvriespotje (bewaarmonster)','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ec50','Nitrificatieremming (op basis van NO2+NO3)','ILOW',494,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('egvv','Elektrisch geleidingsvermogen (EGV)','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('egv25','Elektrisch geleidingsvermogen (EGV)','ILOW',3,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ext450','Extinctiebepaling bij 450nm','ILOW',20,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('feaw','IJzer','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('febs','IJzer','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('feow','IJzer','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('fez1','IJzer','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('fe2o3','IJzer(III)oxide (vrij ijzer, als Fe2O3)','ILOW',10,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('fluorprb-blauw','Fluoroprobe bepaling algengroepen','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('fluorprb-tot','Fluoroprobe bepaling algengroepen','ILOW',17,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('fostac','FOS/TAC ratio','ILOW',8,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('fytop','Fytoplankton','ILOW',155,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('fytop-qsven','Fytoplankton Quick Scan in vennen','ILOW',25,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gcms-bma','Bestrijdingsmiddelen (GCMS)','ILOW',160,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gcms-bma-h','Bestrijdingsmiddelen (GCMS)','ILOW',100,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gcms-bsa','Bijzondere stoffen (GCMS)','ILOW',120,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gcms-bsb','Bijzondere stoffen (GCMS)','ILOW',160,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gcms-fenfta','Alkylfenolen en ftalaten','ILOW',120,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gcms-mpv','Matig Polaire Verbindingen (GCMS)','ILOW',130,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gcms-nts','Bestrijdingsmiddelen NTS (GCMS)','ILOW',300,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gcms-screen','Screening (GCMS)','ILOW',200,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gcms-screenopw','Opwerking Screening (GCMS)','ILOW',80,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gdaw','Gadolinium','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gdow','Gadolinium','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('geur','Geur','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('glds2','Gloeirest van de droge stof (t.b.v. zeefkromme)','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('glind','Percentage gloeirest','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gloeiv','Gloeiverlies (Organische stof zonder correctie voor lutum en vrij ijzer)','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('glonopa','Percentage gloeirest','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('glonopo','Percentage gloeirest','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('glonops','Percentage gloeirest','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('gonsmsem','Fytopl. - bloeisoort (13) Gonyostomum semen','ILOW',30,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('groei','Overmatige groei hogere waterplanten','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('hardhcaco3','Hardheid (als CaCO3)','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('hardheid','Hardheid','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('hco3','Waterstofcarbonaat','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('helder','Helderheid','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('helderv','Helderheid','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('hgaw','Kwik','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('hgbs','Kwik','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('hgow','Kwik','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('hgz1','Kwik','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('hs-bsa','Vluchtige polaire verbindingen','ILOW',65,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ijstsd','IJstoestand / aggregatietoestand van het water','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ind','Droge stof','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ionenratio','Ionenratio','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('kaw','Kalium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('kbs','Kalium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('kgf16','Korrelgroottefractie tot 16 um','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('kgf2','Korrelgroottefractie tot 2 um','ILOW',35,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('kgf32','Korrelgroottefractie tot 32 um','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('kleur','Kleur','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('kleurv','Kleur','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('kow','Kalium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('kroos','Kroos','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('kz1','Kalium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-bmc','Bestrijdingsmiddelen (LCMS)','ILOW',120,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-bmc-h','Bestrijdingsmiddelen (LCMS)','ILOW',75,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-bmd','Bestrijdingsmiddelen (LCMS)','ILOW',160,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-bmd-h','Bestrijdingsmiddelen (LCMS)','ILOW',100,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-bme','Bestrijdingsmiddelen (LCMS)','ILOW',120,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-bme-h','Bestrijdingsmiddelen (LCMS)','ILOW',75,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-bsa','Bijzondere stoffen (LCMS)','ILOW',80,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-bsc','Bijzondere stoffen (LCMS)','ILOW',80,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-bsd','Bijzondere stoffen (LCMS)','ILOW',80,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-gidsstof','Gidsstoffen (LCMS)','ILOW',100,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-gma','Geneesmiddelen (LCMS)','ILOW',120,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-gmb','Geneesmiddelen (LCMS)','ILOW',120,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-gmc','Geneesmiddelen (LCMS)','ILOW',80,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-nts','Bestrijdingsmiddelen NTS (LCMS)','ILOW',300,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-pfasg1','PFAS AS3000 (LCMS)','ILOW',130,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lcms-pfasg2','PFAS overig (LCMS)','ILOW',130,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('liaw','Lithium','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lichtcondities','Lichtcondities doorzicht','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('liow','Lithium','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('locatie','Locatie veldwerkzaamheden','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('macfn-bemuitvf','Macrofauna bemonsteren, uitzoeken en veldformulier','ILOW',305,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('macfn-det','Macrofauna determineren','ILOW',485,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('macfn-qs','Macrofauna quick scan','ILOW',140,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('macfn-qssted','Macrofauna quick scan','ILOW',150,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('macfn-std','Macrofauna standaard','ILOW',790,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('macfn-std-extra','Macrofauna standaard (extra individuen)','ILOW',905,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('macfn-sub','Macrofauna met subbemonstering','ILOW',1015,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('metbeh','Behandeling Metalen Onderzoek','ILOW',45,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mgaw','Magnesium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mgbs','Magnesium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mgow','Magnesium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mgz1','Magnesium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mnaw','Mangaan','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mnbs','Mangaan','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mnow','Mangaan','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mnz1','Mangaan','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('moaw','Molybdeen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mobs','Molybdeen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('monbeh','Behandeling Monster','ILOW',8,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('monb25','Monsterbehandeling – 25 ilowpunten','ILOW',25,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('monb35','Monsterbehandeling – 35 ilowpunten','ILOW',25,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('monb50','Monsterbehandeling – 50 ilowpunten','ILOW',25,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('moow','Molybdeen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('moz1','Molybdeen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mpn_ecoli','Escherichia coli (MPN-methode)','ILOW',36,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mpn_ientro','Intestinale enterococcen (MPN-methode)','ILOW',36,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('mpn_inzet','Inzetten MPN methode','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('naaw','Natrium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('nabs','Natrium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('naow','Natrium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('naz1','Natrium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('neer','Neerslag','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('nh3','Ammoniak','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('nh4','Ammonium (als N)','ILOW',6,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('nh4g','Ammonium (als N)','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('niaw','Nikkel','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('nibs','Nikkel','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('niow','Nikkel','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('niz1','Nikkel','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('nka','Som ammonium- en organisch gebonden stikstof (als N)','ILOW',11,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('nkj','Som ammonium- en organisch gebonden stikstof, Kjeldahl (als N)','ILOW',13,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('nkjg','Stikstof Kjeldahl (als N)','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('not','Som nitraat en nitriet (als N)','ILOW',6,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('no2','Nitriet (als N)','ILOW',6,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('no3','Nitraat (als N)','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('no3g','Nitraat (als N)','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('n_remming','Nitrificatieremming (beperkte proef, op basis van NO2+NO3)','ILOW',119,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('n-snelheid','Nitrificatiesnelheid (als N)','ILOW',86,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ntot','Stikstof totaal','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ocb','Organochloorbestrijdingsmiddelen','ILOW',90,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ocbg','Organochloorbestrijdingsmiddelen','ILOW',90,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ofos','Orthofosfaat (als P)','ILOW',6,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ofosg','Orthofosfaat (als P)','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('olie','Olie','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('oliegc','Minerale olie','ILOW',80,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('oliegcg','Minerale olie','ILOW',80,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('oliegcid','Olie identificatie','ILOW',80,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('oliegrav','Petroleumether extraheerbare oliën en vetten','ILOW',30,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('oliegravg','Petroleumether extraheerbare oliën en vetten','ILOW',30,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('onopa','Onopgeloste stoffen','ILOW',8,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('onopo','Onopgeloste stoffen','ILOW',8,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('onops','Onopgeloste stoffen','ILOW',8,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ostof','Organische stof','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('o2v','Zuurstof','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('o2z','Zuurstof','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pak','Polycyclische aromaten','ILOW',90,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pakg','Polycyclische aromaten','ILOW',90,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pbafwkok76','Afwerking Peilbuis d.m.v. koker doorsnede 76mm','ILOW',27,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pbafwstrk','Afwerking Peilbuis d.m.v. straatkolk','ILOW',11,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pbaw','Lood','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pbbs','Lood','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pbgws','Grondwaterstand Peilbuis t.o.v. bovenkant peilbuis','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pbow','Lood','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pbpl','Plaatsen Peilbuis','ILOW',110,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pbpll','Starttarief Plaatsen Peilbuis','ILOW',180,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pbveld','Veldformulier t.b.v. Peilbuizen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pbz1','Lood','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pcb','Polychloorbifenylen','ILOW',90,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pcbg','Polychloorbifenylen','ILOW',90,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('peilschaalv','Aflezen NAP stand op peilschaal','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ph','Zuurgraad','ILOW',3,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('phh2o','Zuurgraad (pH-H2O)','ILOW',10,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('phv','Zuurgraad','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('planaw','Plannen Afvalwater','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('plandiato','Plannen Diatomeeën','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('plangw','Plannen Grondwater','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('planmacfn','Plannen Macrofauna','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('planow','Plannen Oppervlaktewater','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('plansieragn','Plannen Sieralgen','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('planvegtte','Plannen Vegetatie','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('planz1','Plannen Zuiveringsslib','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('projcoodnte-hybi','Projectcoordinatie Hydrobiologie','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('projh','Projecthandeling','ILOW',25,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pulsen','Aantal pulsen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pulsgen','Aantal pulsen genomen','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('pulsgev','Aantal pulsen gevraagd','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('riscnvcanbtr','Risiconiveau cyanobacteriën','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('saliniteit','Saliniteit','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sbaw','Antimoon','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sbbs','Antimoon','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sbow','Antimoon','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sbz1','Antimoon','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('schuim','Schuim','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('seaw','Selenium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sebs','Selenium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('senskb','Sensor kalibratie','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sensoh','Sensor onderhoud','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('seow','Selenium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sez1','Selenium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sieragn','Sieralgen','ILOW',335,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('snaw','Tin','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('snbs','Tin','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('snow','Tin','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('snz1','Tin','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('so4','Sulfaat','ILOW',9,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('so4g','Sulfaat','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sraw','Strontium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('srow','Strontium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('stroomshd','Stroomsnelheid','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sttlaw','Zwavel','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sttlbs','Zwavel','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sttlow','Zwavel','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sttlz1','Zwavel','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('teaw','Telluur','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tebs','Telluur','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('temp','Temperatuur','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tempkast','Temperatuur kast','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('teow','Telluur','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tez1','Telluur','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tiaw','Titaan','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tic','Anorganisch koolstof (TIC)','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tiow','Titaan','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tiz1','Titaan','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tlaw','Thallium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tlbs','Thallium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tlow','Thallium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tlz1','Thallium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tnb','Totaal organisch en anorganisch gebonden stikstof','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('toc','Totaal organisch koolstof','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('toesgbereenh','Toeslag berekening extra eenheid','ILOW',25,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('toesgbooth','Toeslag monsterneming met boot (inclusief extra persoon)','ILOW',90,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('toesmedwrk','Toeslag monsterneming met extra medewerker ivm veiligheidsaspecten','ILOW',50,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tofos','Orthofosfaat (ongefiltreerd)','ILOW',6,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('totalk','Alkaliniteit','ILOW',8,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('toxblauwalg','Chlorofyl-a geassocieerd met blauwalgen (toetswaarde)','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tpa','Totaal fosfor (als P)','ILOW',11,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('tpag','Totaal fosfor (als P)','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('troealgt','Troebelheid m.b.v. algentoorts','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('troev','Troebelheid','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('uaw','Uranium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('uow','Uranium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('upldndff','Upload biologische gegevens naar NDFF','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('uploadzw','Upload Zwemwaterregister','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vaw','Vanadium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vbs','Vanadium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vcent','Voorbewerking Centrifugeren','ILOW',5,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ve','Vervuilingswaarde','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vegtte','Vegetatie overig','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vegtte-krw','Vegetatie KRW oever en water','ILOW',125,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vegtte-qs','Vegetatie quick scan','ILOW',140,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vegtte-vrst','Vegetatie vooropname vroege soorten','ILOW',75,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('veldbeh','Behandeling Veldwaarnemingen','ILOW',2,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('veldmtgn','Veldmetingen','ILOW',8,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vetid','Vet identificatie','ILOW',80,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vfilt','Filtratie uitgevoerd','ILOW',10,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vlverb','Vluchtige verbindingen','ILOW',80,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vmeng','Mengmonster','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vogl','Vogels','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('volkolf','Volume kolf','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('volvatleeg','Volume vat leeg','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('volvatpr','Volume vat praktisch','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('volvatth','Volume vat theoretisch','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('volvatvol','Volume vat vol','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vow','Vanadium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vpfgh001','Verpakking FGH001','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vpfgh004','Verpakking FGH004','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vpfgh007','Verpakking FGH007','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vpfgh010','Verpakking FGH010','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vpfgh014','Verpakking FGH014','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vpfgh015','Verpakking FGH015','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vpfgh024','Verpakking FGH024','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vpfgh047','Verpakking FGH047','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vporvion100','Verpakking Orvion - 100 ml - bevat conserveringsmiddel (20 ml alcohol)','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vrivm','Verpakking RIVM','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vuil','Vuil','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vzegel','Verzegeling Monsternamekast','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('vz1','Vanadium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('watherkomst','Waterherkomst oppervlaktewater','ILOW',1,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('waw','Wolfraam','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('w_bez volume_veld','Bezinkselvolume na 1/2 uur','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('wbs','Wolfraam','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('wbtoets','Toetsing aan Regeling bodemkwaliteit 2022','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('wbtoetsgbt','Baggerspecie bij GBT in oppervlaktewater (emissiewaarde)','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('wbtoetsgbtlb','Baggerspecie bij GBT op landbodem (emissiewaarde)','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('wbtoetskls','Grond en bagger bij toepassing op of in bodem','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('wbtoetsopp','Bagger en ontvangende bodem bij toepassing in opp.waterl.','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('wbtoetspfas','Toetsing PFAS aan Handelingskader (december 2021)','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('wbveld','Waterbodem veldformulier','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('wbvoor','Waterbodem vooronderzoek','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('w_deelvolume_veld','Aantal ml per deelmonster','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('weercondities','Weercondities doorzicht','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('wow','Wolfraam','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('w_tmax_veld','Maximum temperatuur gekoelde kast','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('w_tmin_veld','Minimum temperatuur gekoelde kast','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('w_tot volume_veld','Totaal monstervolume','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('w_verdunn_veld','Verdunning ingezet voor bezinkselvolume t.b.v. SVI','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('wz1','Wolfraam','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zain','Percentage zandrest','ILOW',15,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zeefkr','Zeefkromme','ILOW',45,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zeefzain','Zeeffractie van de Zandrest','ILOW',60,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('znaw','Zink','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('znbs','Zink','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('znow','Zink','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('znz1','Zink','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zraw','Zirkonium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zrow','Zirkonium','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zwemmjk','Zwemmersjeuk','ILOW',0,'Individueel');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lano01','Anorganisch   (pakket 01)','ILOW',13,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lbac02','Bacteriologisch onderzoek','ILOW',72,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lbest02','Organisch (gezamelijke bestrijdingsmiddelenrapportage)','ILOW',560,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lbest02-h','lbest02-h','ILOW',350,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lglyampa','WRIJ oppervlaktewater glyfosaat-ampa','ILOW',NULL,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lheffing1','Heffing pakket','ILOW',64,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('licpaw','ICP-MS pakket Afvalwater','ILOW',45,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('licpbs','ICP-MS pakket Waterbodem','ILOW',55,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('licpow','ICP-MS pakket Oppervlaktewater, RWZI Influent en Effluent.','ILOW',45,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('licpz1','ICP-MS pakket Slib','ILOW',55,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lkast01','Bemonstering kast','ILOW',0,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lkrwkwart','Kaderrichtlijnen - kwartaalmonster','ILOW',2125,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lkrwmaand','Kaderrichtlijnen - maandmonster','ILOW',1765,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lopp01','Oppervlaktewater   (pakket 01)','ILOW',62,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lopp02','Oppervlaktewater   (pakket 02)','ILOW',65,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lpbblanco','Blanco peilbuizen','ILOW',554,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lslib05','Slib   (pakket 05)','ILOW',26,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lslib06','Slib (pakket 06)','ILOW',110,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ltech01','Technologie   (pakket 01)','ILOW',50,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ltech02','Technologie   (pakket 02)','ILOW',56,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lveldpb','Veldpakket Peilbuizen','ILOW',11,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lveld01','Veldpakket Oppervlaktewater','ILOW',14,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lveld09','Uitgebreid pakket veldmetingen','ILOW',14,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lvzw01','Veldpakket Zwemwater','ILOW',14,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lwbc1','Waterbodempakket C1, Regeling bodemkwaliteit 2022','ILOW',596,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lwbregwat','Waterbodem pakket Regionale Wateren','ILOW',506,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sap_bijzstffn','sap_bijzstffn','ILOW',240,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sap_geneesm','sap_geneesm','ILOW',240,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sap_lcmsbmde','sap_lcmsbmde','ILOW',280,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sapnf_cadmiumhh','sapnf_cadmiumhh','ILOW',45,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sapnf_macroion','sapnf_macroion','ILOW',45,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sap_nh4nh3','sap_nh4nh3','ILOW',13,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sap_niettoetsb','sap_niettoetsb','ILOW',600,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sap_ptotntot','sap_ptotntot','ILOW',50,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sap_vldbasis','sap_vldbasis','ILOW',12,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sap_vldbio','sap_vldbio','ILOW',14,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('sap_waterkrktr','sap_waterkrktr','ILOW',28,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yat','WRIJ at','ILOW',13,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yat-veld','WRIJ at veldmetingen','ILOW',4,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ycos','WRIJ cos','ILOW',35,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ycp1','WRIJ compost cluster 1','ILOW',20,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ycp1dun','WRIJ compost cluster1 vloeibaar slib','ILOW',13,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ycp2','WRIJ compost cluster 2','ILOW',55,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ycp3','WRIJ compost cluster 3','ILOW',60,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ydoc_hh','WRIJ doc_hardheid','ILOW',17,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yef-veld','WRIJ effluent veldmetingen','ILOW',2,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yef0','WRIJ effluent gezamenlijk','ILOW',75,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yinf','WRIJ influent, deelstromen, voorbezink','ILOW',50,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yinfl-mbs','WRIJ influent mbs','ILOW',59,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yinfl-plus','WRIJ obg infl aviko, obg centraat, ltv infl iwl','ILOW',63,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yinfl-zpn-vw2','WRIJ influent zpn vw2','ILOW',69,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yinf-veld','WRIJ influent veldmetingen','ILOW',2,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yint-stromen','WRIJ internestromen','ILOW',36,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ynutr','WRIJ oppervlaktewater nutrienten','ILOW',42,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yow','WRIJ oppw','ILOW',71,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('ysg','WRIJ slibgisting','ILOW',10,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yveld-algea','WRIJ veldpakket Algeatorch metingen','ILOW',24,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yveld-chemie','WRIJ oppervlaktewater veld-chemie','ILOW',12,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yveld-gw','WRIJ grondwater veld','ILOW',8,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yveld-zw','WRIJ zwemwater veldmetingen','ILOW',12,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yzm8-ef','WRIJ 8x metalen effl.','ILOW',45,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yzm8-in','WRIJ influent 8x metalen','ILOW',45,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('yzs','WRIJ zuiveringsslib','ILOW',95,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zov1','ZZL opp.water veld 1','ILOW',12,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zo30','ZZL opp.water 30 (onop)','ILOW',13,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zrv1','ZZL techn. veld 1','ILOW',4,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zr02','ZZL technologie 2','ILOW',47,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zr03','ZZL technologie 3','ILOW',80,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zr04','ZZL technologie 4','ILOW',75,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zr05','ZZL technologie 5','ILOW',38,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zr06','ZZL technologie 6','ILOW',56,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zr07','ZZL technologie  7','ILOW',301,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zr08','ZZL technologie 8','ILOW',296,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zs02','ZZL techn. slib 2','ILOW',75,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('zs05','ZZL techn. slib 5','ILOW',50,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('licpow_nf','ICP-MS pakket Oppervlaktewater, RWZI Influent en Effluent. Na filtratie','ILOW',45,'Pakket');
INSERT INTO tblMeetpakketten(Naam,Omschrijving,Valuta,Stukprijs,Type) VALUES ('lglyampa','glyfosaat en AMPA meting','ILOW',300,'Pakket');
